Update test8

diff --git a/test8 b/test8
--- a/test8
+++ b/test8
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# seafile-server-installer/seafile-ubuntu
+# seafile-server-installer/seafile-8.0_ubuntu
 #
 # Copyright 2015, Alexander Jackson <alexander.jackson@seafile.de>
 # Copyright 2016, Zheng Xie <xie.zheng@seafile.com>
@@ -30,14 +30,70 @@ fi
 set -e
 
 if [[ "$#" -ne 1 ]]; then
-    echo "You must specify Seafile version to install"
-    echo "Like: $0 7.0.0"
+    echo "You must specif Seafile version to install"
+    echo "Like: $0 8.0.0"
     exit 1
 fi
 
 clear
+cat <<EOF
 
-echo "This script will install Seafile Community Edition for you."
+  This script installs the community edition of the Seafile Server on a Ubuntu 16.04 (Xenial) 64bit
+  - Newest Seafile server version, MariaDB, Memcached, NGINX -
+  -----------------------------------------------------------------
+
+  This installer is meant to run on a freshly installed machine
+  only. If you run it on a production server things can and
+  probably will go terribly wrong and you will lose valuable
+  data!
+
+  For questions or suggestions please contact us at
+  support@seafile.com
+
+  -----------------------------------------------------------------
+
+  Possible options:
+  1 = Seafile Community (Free) Edition (CE)
+  2 = Seafile Professional Edition (PRO)
+
+EOF
+
+if [[ ${SEAFILE_PRO} == "" ]]; then
+    PS3="Which Seafile version would you like to install? "
+    select SEAFILE_SERVER_VERSION in CE PRO ABORT; do
+        case "${SEAFILE_SERVER_VERSION}" in
+            ABORT)
+                echo "Aborting"
+                break
+                ;;
+            "")
+                echo "$REPLY: Wrong value. Select 1 or 2."
+                ;;
+            *)
+                if [[ ${SEAFILE_SERVER_VERSION} = "PRO" ]]; then
+                    SEAFILE_PRO=1
+                else
+                    SEAFILE_PRO=0
+                fi
+                break
+        esac
+    done
+fi
+
+is_pro() {
+    if [[ "$SEAFILE_PRO" == "1" ]]; then
+        return 0
+    else
+        return 1
+    fi
+}
+
+echo
+if is_pro; then
+    echo "This script will install Seafile Professional Edition for you."
+else
+    echo "This script will install Seafile Community Edition for you."
+fi
 echo
 
 # -------------------------------------------
@@ -50,10 +106,20 @@ IP_OR_DOMAIN=127.0.0.1
 SEAFILE_VERSION=$1
 TIME_ZONE=Europe/Berlin
 
-
-SEAFILE_SERVER_PACKAGE=seafile-server_${SEAFILE_VERSION}_x86-64.tar.gz
-SEAFILE_SERVER_PACKAGE_URL=https://download.seadrive.org/${SEAFILE_SERVER_PACKAGE}
-INSTALLPATH=${SEAFILE_SERVER_HOME}/seafile-server-${SEAFILE_VERSION}/
+if is_pro; then
+    SEAFILE_SERVER_PACKAGE=seafile-pro-server_${SEAFILE_VERSION}_x86-64.tar.gz
+    if [[ ! -e /opt/$SEAFILE_SERVER_PACKAGE ]]; then
+        echo
+        echo "You must download \"$SEAFILE_SERVER_PACKAGE\" to the /opt/ folder before running this script!"
+        echo
+        exit 1
+    fi
+    INSTALLPATH=${SEAFILE_SERVER_HOME}/seafile-pro-server-${SEAFILE_VERSION}/
+else
+    SEAFILE_SERVER_PACKAGE=seafile-server_${SEAFILE_VERSION}_x86-64.tar.gz
+    SEAFILE_SERVER_PACKAGE_URL=https://download.seadrive.org/${SEAFILE_SERVER_PACKAGE}
+    INSTALLPATH=${SEAFILE_SERVER_HOME}/seafile-server-${SEAFILE_VERSION}/
+fi
 
 
 # -------------------------------------------
@@ -80,38 +146,19 @@ then
   echo "Aborting because user ${SEAFILE_SERVER_USER} already exist" ; exit 1
 fi
 
-
 # -------------------------------------------
 # Additional requirements
 # -------------------------------------------
 apt-get update
 
-if [[ ${SEAFILE_VERSION} =~ 8\.[0-9]*\.[0-9]* ]]; then
-	apt-get install -y python3 python3-setuptools python3-pip sudo \
-	openjdk-11-jre memcached libmemcached-dev zlib1g-dev pwgen curl openssl poppler-utils libpython2.7 libreoffice \
-	libreoffice-script-provider-python ttf-wqy-microhei ttf-wqy-zenhei xfonts-wqy nginx
+apt-get install -y python3 python3-setuptools python3-pip python3-ldap memcached openjdk-11-jre \
+    libmemcached-dev libreoffice-script-provider-python libreoffice pwgen curl nginx libmysqlclient-dev
 
-	pip3 install --timeout=3600 Pillow pylibmc captcha jinja2 sqlalchemy==1.4.3 \
-	django-pylibmc django-simple-captcha python3-ldap
-else
-	if [[ ${SEAFILE_VERSION} =~ 7\.1[0-9]*\.[0-9]* ]]; then
-		apt-get install -y python3 python3-setuptools python3-pip sudo \
-		openjdk-11-jre memcached libmemcached-dev zlib1g-dev pwgen curl openssl poppler-utils libpython2.7 libreoffice \
-		libreoffice-script-provider-python ttf-wqy-microhei ttf-wqy-zenhei xfonts-wqy nginx
-	
-		pip3 install --timeout=3600 Pillow pylibmc captcha jinja2 sqlalchemy \
-		django-pylibmc django-simple-captcha python3-ldap
-	else
-		apt-get install -y python2.7 sudo python-pip python-setuptools python-mysqldb python-ldap python-urllib3 \
-		openjdk-11-jre memcached libmemcached-dev zlib1g-dev pwgen curl openssl poppler-utils libpython2.7 libreoffice \
-		libreoffice-script-provider-python ttf-wqy-microhei ttf-wqy-zenhei xfonts-wqy nginx python-requests
+pip3 install --timeout=3600 django==2.2.* future mysqlclient pymysql Pillow pylibmc captcha jinja2 sqlalchemy==1.4.3 \
+    psd-tools django-pylibmc django-simple-captcha
 
-		pip install pylibmc==1.6.0 django-pylibmc==0.6.1
-		pip install --timeout=3600 Pillow==4.3.0
-		pip install psd-tools==1.4
-	fi
-fi
 
+service memcached start
 
 
 # -------------------------------------------
@@ -152,7 +199,6 @@ server {
          proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
          proxy_connect_timeout  36000s;
          proxy_read_timeout  36000s;
-         proxy_request_buffering    off;
 
         access_log      /var/log/nginx/seafhttp.access.log seafileformat;
         error_log       /var/log/nginx/seafhttp.error.log;
@@ -161,18 +207,13 @@ server {
         root ${SEAFILE_SERVER_HOME}/seafile-server-latest/seahub;
     }
     location /seafdav {
-        fastcgi_pass    127.0.0.1:8080;
-        fastcgi_param   SCRIPT_FILENAME     \$document_root\$fastcgi_script_name;
-        fastcgi_param   PATH_INFO           \$fastcgi_script_name;
-        fastcgi_param   SERVER_PROTOCOL     \$server_protocol;
-        fastcgi_param   QUERY_STRING        \$query_string;
-        fastcgi_param   REQUEST_METHOD      \$request_method;
-        fastcgi_param   CONTENT_TYPE        \$content_type;
-        fastcgi_param   CONTENT_LENGTH      \$content_length;
-        fastcgi_param   SERVER_ADDR         \$server_addr;
-        fastcgi_param   SERVER_PORT         \$server_port;
-        fastcgi_param   SERVER_NAME         \$server_name;
-        fastcgi_param   REMOTE_ADDR         \$remote_addr;
+        proxy_pass         http://127.0.0.1:8080/seafdav;
+        proxy_set_header   Host \$host;
+        proxy_set_header   X-Real-IP \$remote_addr;
+        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
+        proxy_set_header   X-Forwarded-Host \$server_name;
+        proxy_set_header   X-Forwarded-Proto \$scheme;
+        proxy_read_timeout  1200s;
 
         client_max_body_size 0;
 
@@ -196,6 +237,7 @@ then
   SQLROOTPW=`sed -n 's/password=//p' /root/.my.cnf`
 else
   DEBIAN_FRONTEND=noninteractive apt-get install -y mariadb-server
+  service mysql start
 
   SQLROOTPW=$(pwgen)
 
@@ -211,78 +253,52 @@ EOF
 fi
 
 # -------------------------------------------
-# Seafile init script // Seafile Server Autostart + Scripte
+# Seafile init script
 # -------------------------------------------
-cat > /etc/systemd/system/seafile.service <<'EOF'
-[Unit]
-Description=Seafile Server
-After=network.target mysql.service
-
-[Service]
-Type=oneshot
-ExecStart=/opt/seafile/seafile-server-latest/seafile.sh start
-ExecStop=/opt/seafile/seafile-server-latest/seafile.sh stop
-RemainAfterExit=yes
-User=seafile
-Group=nogroup
-
-[Install]
-WantedBy=multi-user.target
-EOF
-systemctl enable seafile
-cat > /etc/systemd/system/seahub.service <<'EOF'
-[Unit]
-Description=Seafile Seahub
-After=network.target seafile.service
-
-[Service]
-ExecStart=/opt/seafile/seafile-server-latest/seahub.sh start
-ExecStop=/opt/seafile/seafile-server-latest/seahub.sh stop
-User=seafile
-Group=nogroup
-Type=oneshot
-RemainAfterExit=yes
-
-[Install]
-WantedBy=multi-user.target
-EOF
-systemctl enable seahub
-
-# Seafile restart script
-cat > /usr/local/sbin/seafile-server-restart << 'EOF'
+cat > /etc/init.d/seafile-server << EOF
 #!/bin/bash
-for ACTION in stop start ; do
-    for SERVICE in seafile seahub ; do
-      systemctl ${ACTION} ${SERVICE}
-    done
-done
+### BEGIN INIT INFO
+# Provides:          seafile-server
+# Required-Start:    \$remote_fs \$syslog mysql
+# Required-Stop:     \$remote_fs \$syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: Seafile server
+# Description:       Start Seafile server
+### END INIT INFO
+
+# Author: Zheng Xie <xie.zheng@seafile.com>
+
+# Change the value of "seafile_dir" to your path of seafile installation
+user=${SEAFILE_SERVER_USER}
+seafile_dir=${SEAFILE_SERVER_HOME}
+script_path=\${seafile_dir}/seafile-server-latest
+seafile_init_log=\${seafile_dir}/logs/seafile.init.log
+seahub_init_log=\${seafile_dir}/logs/seahub.init.log
+
+
+case "\$1" in
+        start)
+                sudo -u \${user} \${script_path}/seafile.sh start >> \${seafile_init_log}
+                sudo -u \${user} \${script_path}/seahub.sh start >> \${seahub_init_log}
+        ;;
+        restart)
+                sudo -u \${user} \${script_path}/seafile.sh restart >> \${seafile_init_log}
+                sudo -u \${user} \${script_path}/seahub.sh restart >> \${seahub_init_log}
+        ;;
+        stop)
+                sudo -u \${user} \${script_path}/seafile.sh \$1 >> \${seafile_init_log}
+                sudo -u \${user} \${script_path}/seahub.sh \$1 >> \${seahub_init_log}
+        ;;
+        *)
+                echo "Usage: /etc/init.d/seafile-server {start|stop|restart}"
+                exit 1
+        ;;
+esac
 EOF
 
-chmod 700 /usr/local/sbin/seafile-server-restart
-
-# Seafile start script
-cat > /usr/local/sbin/seafile-server-start << 'EOF'
-#!/bin/bash
-for ACTION in start ; do
-    for SERVICE in seafile seahub ; do
-      systemctl ${ACTION} ${SERVICE}
-    done
-done
-EOF
-
-chmod 700 /usr/local/sbin/seafile-server-start
-
-# Seafile stop script
-cat > /usr/local/sbin/seafile-server-stop << 'EOF'
-#!/bin/bash
-for ACTION in stop ; do
-    for SERVICE in seafile seahub ; do
-      systemctl ${ACTION} ${SERVICE}
-    done
-done
-EOF
-
-chmod 700 /usr/local/sbin/seafile-server-stop
+chmod +x /etc/init.d/seafile-server
+update-rc.d seafile-server defaults
 
 
 # -------------------------------------------
@@ -290,7 +306,7 @@ chmod 700 /usr/local/sbin/seafile-server-stop
 # -------------------------------------------
 mkdir -p ${SEAFILE_SERVER_HOME}/installed
 cd ${SEAFILE_SERVER_HOME}
-if [[ ! -e /opt/${SEAFILE_SERVER_PACKAGE} ]]; then
+if ! is_pro && [[ ! -e /opt/${SEAFILE_SERVER_PACKAGE} ]]; then
     curl -OL ${SEAFILE_SERVER_PACKAGE_URL}
 else
     cp /opt/${SEAFILE_SERVER_PACKAGE} .
@@ -411,21 +427,34 @@ eval "sed -i 's/= ask_admin_password()/= \"${SEAFILE_ADMIN_PW}\"/' ${INSTALLPATH
 # -------------------------------------------
 # Start and stop Seafile eco system. This generates the initial admin user.
 # -------------------------------------------
-echo "hier bin ich 1"
 chown ${SEAFILE_SERVER_USER}:${SEAFILE_SERVER_USER} -R ${SEAFILE_SERVER_HOME}
-${INSTALLPATH}/seafile.sh start
-${INSTALLPATH}/seahub.sh start
-echo "hier bin ich 2"
-sleep 2                         # sleep for a while, otherwise seahub will not be stopped
-${INSTALLPATH}/seahub.sh stop
+
+su - seafile -c "${INSTALLPATH}/seafile.sh start"
+wait
+su - seafile -c "${INSTALLPATH}/seahub.sh start"
+wait					# sleep for a while, otherwise seahub will not be stopped
+su - seafile -c "${INSTALLPATH}/seahub.sh stop"
+wait
+su - seafile -c "${INSTALLPATH}/seafile.sh stop"
+wait
 sleep 1
-${INSTALLPATH}/seafile.sh stop
-echo "hier bin ich 3"
 
 # -------------------------------------------
 # Restore original check_init_admin.py
 # -------------------------------------------
 mv ${INSTALLPATH}/check_init_admin.py.backup ${INSTALLPATH}/check_init_admin.py
+
+if is_pro; then
+    PRO_PY=${INSTALLPATH}/pro/pro.py
+    $PYTHON ${PRO_PY} setup --mysql --mysql_host=127.0.0.1 --mysql_port=3306 --mysql_user=seafile --mysql_password=${SQLSEAFILEPW} --mysql_db=seahub_db
+fi
+
+# kill all process
+sleep 1
+service seafile-server stop
+wait
+sleep 1
+
 
 # -------------------------------------------
 # Fix permissions
@@ -435,35 +464,12 @@ if [[ -d /tmp/seafile-office-output/ ]]; then
     chown ${SEAFILE_SERVER_USER}:${SEAFILE_SERVER_USER} -R /tmp/seafile-office-output/
 fi
 
-
-# -------------------------------------------
-# Database Backup
-# -------------------------------------------
-# install package
-apt-get install automysqlbackup -y
-
-# change destination directory
-SEAFILE_SERVER_BACKUPDIR="/var/backups/seafile-server/database/"
-eval "sed -i 's#/var/lib/automysqlbackup#$SEAFILE_SERVER_BACKUPDIR#' /etc/default/automysqlbackup"
-
-# launch a backup now
-/usr/sbin/automysqlbackup
-
-echo "Automatic database backups are in ${SEAFILE_SERVER_BACKUPDIR}."
-
 # -------------------------------------------
 # Start seafile server
 # -------------------------------------------
 echo "Starting productive Seafile server"
-service seafile start
-service seahub start
-
-
-# -------------------------------------------
-# Install GParted
-# -------------------------------------------
-echo "Installing GParted"
-apt-get install gparted -y
+service seafile-server restart
+wait
 
 
 # -------------------------------------------
